### ISSUE TITLE
Wifi Scan Not Showing all Access Point

### ISSUE THREAD

**Issue by hallard** [mathieucarbou/YaSolR#33]
**Firmware**

Pro Latest current version `main_3e0e883`

**Board**

Tiny Pico and ESP32 Clone totally different boards

**Description**

On first boot during setup when device shows AP, WifiScan seems broken, I mean I don't see my Wifi AP and I see only one (near my router) with very Week signal

**Additional notes**

I tried few days ago with another ESP32 board type and already noticed this issue, though it was the board, but today with another board type same issue. I succeeded do configure setting the board 1 meter from the router (since I can't setup manual SSID on captive portal screen)

Once configured all is fine it's really related to captive portal Wifi Scan I think, I suspect a misconfiguration of wifi power or bad parameter when issuing WifiScan

Trust me I may have done this scan from my desktop office at least 500 times in my life on a huge ESP devices, it's the first time it does not work from there.

**Comment by mathieucarbou** [comment]
> Once configured all is fine it's really related to captive portal Wifi Scan I think, I suspect a misconfiguration of wifi power or bad parameter when issuing WifiScan

For the captive portal I am using [MycilaESPConnect](https://github.com/mathieucarbou/MycilaESPConnect/), which is based on https://github.com/ayushsharma82/ESPConnect, which has a long history and code is the same. The only issue so far was sometimes not being able to see some SSID for mesh networks.

I know there is some scan issues sometimes on esp32 boards depending on the config, what is hard for me is to reproduce: I was not able to reproduce any of them for now.

For the captive portal, I know that depending when the scan is triggered, sometimes is does not see everything at first, and you need to click on the scan button to trigger a new scan and wait for the new results. I guess you already tried ?

Also, the ones not showing are of course 2.4Ghz networks right ?

For YaSolR, if you pick another board, make sure you run on a dual-core esp32, otherwise the measurement tasks and routing tasks will be impacted by the Dashboard refresh and MQTT publications if you activate it.

I will try to do some research and see what I can improve...

On your side, would you be able to try one of the example in this project:

https://github.com/mathieucarbou/MycilaESPConnect/tree/main/examples

And tell me if you can reproduce ?

And if you can, would you be ok to help me test the few changes I would try ?

thanks!

**Comment by hallard** [comment]
Hey good to know for dual core, could avoid me some pain in the future.

yes of course I can do that, not over this week end but may be later night from monday.

**Comment by hallard** [comment]
@mathieucarbou just tested sample `AdvancedCaptivePortal`,  just works ROOB, I'm seeing all 3 SSID I usually see. 

When I triggered the issue I was seeing only one with 6% and now it's 22%. 

But now looking what I'm seeing, I think I got it, I don't see my neighbor AP that I was seeing when I got the issue. There is an option on Wifi setting to rescan all 2.4 channels and not using only default (or last), if not activated if scan only channel of where it was connected last time. But as it's factory FW, it is merely on default one that does not fit my band and WiFi Scan disable, I bet it's the issue, I already add this one in Tasmota and needed to `setoption 56 1` when moving same wifi SSID from one house to another 
https://tasmota.github.io/docs/Commands/#setoption56`

**Comment by hallard** [comment]
Tested both blocking and nonBlocking samples both working fine.

Just a little strange behavior on all except for Blocking mode, I need to click twice on refresh button, because 1st click launch a very very quick rescan (soooo quick, than does not change anything) and on 2nd click takes few seconds and works. Then after always need to click twice for correct rescan.

**Comment by mathieucarbou** [comment]
I did a bit of digging and testing with the same example also. Here are my findings:

- The WiFi scan code I was using is exactly the same as what we can find in Arduino examples, ESPConnect original repo and NetWizard libraries. So all these, including Arduino examples, behave the same way 

- I've looked at the ESPHome code base on ESP-IDF to compare their code with the Arduino core implementation (using ESP-IDF too) and they use strictly exactly the same code in the same sequence

- But... I discovered some UX issues cause by the fact that a new scan was started in background as soon as we got some results, causing clicking next not refreshing the results. I've fixed that and now the UI is waiting for the results, and clicking next will trigger a new scan, which will wait for the results again.

- For Tasmota,  `setoption 56 1` does not impact the captive portal network scan but the ability to ensure the network we want to connect to at startup is correctly found. But this is valid **ONLY** if you tell the ESP32 to save the WiFi ssid and credentials (which is done by default), but in YaSolR or in any of these network manager libraries, the persistent mode is not set and the WiFi creds, even if there were some saved in NVS, won't be recalled.

So I have released a new version, which I've just integrated in YaSolR now. 

A build in in progress for the OSS and Pro firmware, should be ready in ~ 20 min or less.

**Comment by mathieucarbou** [comment]
> Just a little strange behavior on all except for Blocking mode, I need to click twice on refresh button, because 1st click launch a very very quick rescan (soooo quick, than does not change anything) and on 2nd click takes few seconds and works. Then after always need to click twice for correct rescan.

That's exactly the UI glitch I was talking about ;-) You found it ;-)

**Comment by hallard** [comment]
Thanks for this investigation and fix.
something that I don't explain (and that may explain only by a bad band scan or scan start for lower bands and never had time to scan higher bands) due to "glitch bug"? 
but with "glitch bug" all samples I tested where seeing my AP and only the pro version and oss version binary build I flashed never see my AP that is very strange.
Anyway let's wait for new build, would be a great test.

**Comment by mathieucarbou** [comment]
> Thanks for this investigation and fix. something that I don't explain (and that may explain only by a bad band scan or scan start for lower bands and never had time to scan higher bands) due to "glitch bug"? but with "glitch bug" all samples I tested where seeing my AP and only the pro version and oss version binary build I flashed never see my AP that is very strange. Anyway let's wait for new build, would be a great test.

Yes! I think the UI caused the issue. But when fixing that, I saw that clicking on the scan button to trigger a complete new scan will go again through all the channels (I am not doing a fast scan), and will now wait for the scan to complete. In my test though, sometimes some AP were not found also, some yes. But clicking on refresh would then find them. I don't explain this fact.  I am using the same code as other people, so the only explanation I could come up with, is that wifi scanning consumes a lot of power so, as the Arduino core example readme say, we should ensure a stable / reliable power source.

**Comment by hallard** [comment]
just tested new pro build, glitch bug have gone but still scan not showing issue, here example of multiple scans, my AP is CH2I-HOTSPOT 61% when seen so should always be there (issue tested flashing factory firmware to fresh start)

Here what I've got here 
![image](https://github.com/user-attachments/assets/abd0810d-6767-473f-a155-ca069baf916a)


**From factory pro**
![image](https://github.com/user-attachments/assets/b9bf60fe-077c-4633-884c-b58b83766601)
![image](https://github.com/user-attachments/assets/bd2bb95f-6b9f-4cdc-863a-1e1819fae37c)
![image](https://github.com/user-attachments/assets/97be47af-79f8-4d77-a804-0477bb224d64)
![image](https://github.com/user-attachments/assets/025b1a41-5147-48aa-b513-abb4feecc4b9)

**And below the same with sample `AdvancedCaptivePortal` of `MycilaESPConnect` `6.0.2`** build and flashed from VScode

![image](https://github.com/user-attachments/assets/2a4021c2-4b8e-430a-920b-173999e8e658)
![image](https://github.com/user-attachments/assets/5f4eca88-a62b-4ca0-bf97-4e0b7a33677a)
![image](https://github.com/user-attachments/assets/7a5b8660-df37-4d7f-b4ce-5b2322bc1703)


I think it may be not code related but default settings, do you know how can i Get factory image for `AdvancedCaptivePortal` just to be sure?

**Comment by mathieucarbou** [comment]
Yes I have the same behavior. There is only one scan network method in Arduino and it returns I consistent results also at home. I have to click on refresh. This is not a blocker, as long as the said is found.

To completely erase an esp we can do `esptool.py erase_flash` , then re-upload the firmware.

**Comment by hallard** [comment]
tried to reflash factory, this time worked, you're correct looks like standard behavior.

As you said since one or two refresh does the trick, we can close this one, thanks for investigating.
