### ISSUE TITLE
last build, not reading remote JSY data anymore

### ISSUE THREAD

**Issue by hallard** [mathieucarbou/YaSolR#38]
**Firmware**

Latest pro ESP32 dev FW (as today)
`YaSolR-main-pro-esp32-en.FACTORY`

**Board**

ESP32 DEV

**hardware setup**

Nothing all disabled

**Description**

Looks like latest build does not read values of remote JSY, my remote JSY works, get data into node red, before yasolr was gathering same data from remote jsy, looks like not doing anymore.

**Screenshots**

![image](https://github.com/user-attachments/assets/7335170d-d0a2-4801-8d62-f7f8988958e0)

![image](https://github.com/user-attachments/assets/3ef67c18-bd47-4d6f-8dcb-18f3786ea6cc)

**Comment by hallard** [comment]
Nice, this mean we need to wait a little until it's done to get it back to work?

No hurry on my side, I was just testing and wanted to mention.

**Comment by mathieucarbou** [comment]
Yes, tomorrow YaSolR will be compatible with latest version of MycilaJSY. Right now it requires version 10.x.x.
There has been some required api changes for the support of 333.

**Comment by mathieucarbou** [comment]
Mycila JSY 11.x ready: https://github.com/mathieucarbou/MycilaJSY/releases

**Comment by mathieucarbou** [comment]
and new yasolr firmwares are being generated. I will close this ;-)
